import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/contexts/cartcontext";
import { LoginProvider } from "@/contexts/logincontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LoginProvider>
      <CartProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </CartProvider>
    </LoginProvider>
  );
}
